version: 2

build:
  os: "ubuntu-24.04"
  tools:
    python: "3.12"
  jobs:
    pre_install:
      - pip install mkdocs
      - pip install mkdocs-material
      - pip install mkdocs-static-i18n
      - pip install mkdocs-git-revision-date-localized-plugin
      - pip install mkdocs-git-authors-plugin
      - pip install mkdocs-izsam-video

mkdocs:
  configuration: mkdocs.yml